PROG=../../../../bin/7za$(BINSUFFIX)

LOCAL_FLAGS= \
  -DBREAK_HANDLER \
  -DUNICODE -D_UNICODE

include ../../../../makefile.crc32
include ../../../../makefile.machine

PCH_NAME=$(PRE_COMPILED_HEADER)

LIBS=$(LOCAL_LIBS)

include ../../../../makefile.glb

