PROG=../../../../bin/7zr$(BINSUFFIX)

LOCAL_FLAGS= -D_NO_CRYPTO -DBREAK_HANDLER -DUNICODE -D_UNICODE

include ../../../../makefile.crc32
include ../../../../makefile.machine

PCH_NAME=$(PRE_COMPILED_HEADER)

LIBS=$(LOCAL_LIBS)

include ../../../../makefile.glb

