PROG=../../../../bin/7zCon.sfx

LOCAL_FLAGS= \
  -DEXTRACT_ONLY \
  -DNO_READ_FROM_CODER \
  -D_SFX \
  -DUNICODE -D_UNICODE

include ../../../../makefile.crc32
include ../../../../makefile.machine

PCH_NAME=$(PRE_COMPILED_HEADER)

LIBS=$(LOCAL_LIBS)

include ../../../../makefile.glb

